sudo: required

addons:
  apt:
    sources:
      - chef-stable-precise
    packages:
      - chefdk
      - vagrant

branches:
  only:
    - master

env:
  global:
    # Ignore warnings when running specs.
    - RUBYOPT="-W0"
  matrix:
    - CHEF_VERSION=latest PLATFORM=debian-7
    - CHEF_VERSION=latest PLATFORM=debian-8
    - CHEF_VERSION=latest PLATFORM=ubuntu-1204
    - CHEF_VERSION=latest PLATFORM=ubuntu-1404
    - CHEF_VERSION=latest PLATFORM=centos-6
    - CHEF_VERSION=latest PLATFORM=centos-7

matrix:
  fast_finish: true

# Ensure we make ChefDK's Ruby the default
before_script:
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  # We have to install chef-sugar for ChefSpec
  - /opt/chefdk/embedded/bin/chef gem install chef-sugar
  # Ensure kitchen-docker is available for testing
  - /opt/chefdk/embedded/bin/chef gem install kitchen-vagrant
script:
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/rubocop --version
  - /opt/chefdk/embedded/bin/rubocop
  - /opt/chefdk/embedded/bin/foodcritic --version
  - /opt/chefdk/embedded/bin/foodcritic .
  - /opt/chefdk/embedded/bin/kitchen --version
  - /opt/chefdk/embedded/bin/kitchen verify "$PLATFORM"
